### ISSUE TITLE
Bugsack error on loading

### ISSUE THREAD

**Issue by milestorme** [InfiniteLoopAlchemist/CritMatic#7]
Error on Classic version 1.15.8

2x CritMatic/Modules/CritMaticOptions.lua:35: hooksecurefunc(): InterfaceOptionsList_DisplayPanel is not a function

This prevents moving the on-screen window

CritMatic/Modules/CritMaticOptions.lua

`hooksecurefunc("InterfaceOptionsList_DisplayPanel", function(frame)`

Minimal safe fix (works on Classic 1.15.8 + anything else)

Guard the hook so it only runs if the function exists:

```
-- Hook into the Blizzard options panel (only on builds where this function exists).
if type(InterfaceOptionsList_DisplayPanel) == "function" then
    hooksecurefunc("InterfaceOptionsList_DisplayPanel", function(frame)
        if frame == blizzPanel then
            --
        end
    end)
end
```

https://github.com/InfiniteLoopAlchemist/CritMatic/pull/8
